############################ Default configuration #########################
baseURL = "http://web.hugity.com/j575601a440j7gar80499999sn7pvvdq/"
languageCode = "en-us"
# site title 
title = "Northendlab | Blog Template"
# theme
theme = "northendlab-light-hugo"
# post pagination
pagination.pagerSize = "5"
# post excerpt
summaryLength = "10"
# disqus short name
[services.disqus]
shortname = 'themefisher-template'
